name: myblog
services: 
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=wordpress
    volumes: 
      - mysql-data:/var/lib/mysql
      - /app/mysqlconf:/etc/mysql/conf.d
    restart: always
    networks: 
      - mynet
    
  wordpress: 
    container_name: mywordblog
    image: wordpress:latest
    ports:
      - "9090:80"
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=123456
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    restart: always
    networks:
      - mynet
    depends_on:
      - mysql
volumes:
  mysql-data:
  wordpress:
networks:
  mynet:
